version: "3"
services:
  react-ui:
    build:
      context: .
    ports:
      - "3009:3000"
    container_name: react-ui
    stdin_open: true
    networks:
      - react-network
    volumes:
      - ./react-auth:/app
      - /app/node_modules

networks:
  react-network:
    driver: bridge
